app:
  name: <%= cmp %>
  title: АРМ сотрудника службы поддержки
  url:
    rest: '/api/rest'

  messages:
    notFound: 'Ничего не найдено'
    notFoundDetail: '<p>Мы искали то, что вы просили, но к сожалению ничего не смогли найти.</p>
               <p>Это могло произойти в случае, если в учетных системах нет данных об искомом объекте,
               или если вы немного ошиблись при вводе. На всякий случай, посмотрите внимательно,
               вверно ли вы ввели свой запрос.</p>'
    certificateNotFound: 'Сертификат не найден'
    flkNotFound: 'Файл архив заявки не найден'

mod:
  scroll:
    up:
       marginRight: 170
       marginBottom: 48
    to:
      animateTime: 300
      offset: 220
    area:
      top: null
